### ISSUE TITLE
Multiple issues importing CSV

### ISSUE THREAD

**Issue by verchalent** [assetgrid/assetgridapp#39]
Our goal is for Assetgrid's CSV importer to be flexible enough to import any CSV file, but we know that some banks aren't exactly keen on following standards.

**Describe the issue**
What is the problem when importing the CSV file?
1. Importer does not understand common US date format (MM/dd/yyyy)
2. Importer does not allow for files with withdrawals and deposits in separate cols

**Describe what is needed to resolve the issue**
What do you think it would take to be able to import the CSV file. How can it be integrated into the existing process?
1. This would be solved by recognizing common formats used in the US
2. This would be solved by allowing separate cols for withdraws and deposits (also it would be nice to have balance to rationalize).

**Upload a sample**
[test.csv](https://github.com/assetgrid/assetgridapp/files/9793018/test.csv)

**Comment by alex6480** [comment]
You can use any date format you want. There is a link to a website with information about how to enter the American format correctly on the import page.

The development build supports separate withdrawal/deposit columns. It'll be available in the next release.

The idea about using the balance column is interesting . I need to spend more time thinking about how to use it. Whether it should just be a way to double check that the amount is correct, or whether it could be an alternative way to calculate amount.

**Comment by verchalent** [comment]
Sorry, to clarify, the date format detection does not work. If I specify the column and the format manually, it is then detected as expected.

**Comment by alex6480** [comment]
There is no date format detection. But you're right. That sounds like a good idea.

Do you mind making separate feature requests for the balance idea and auto-detection of date format? Otherwise I will do it later, it's just that I am on my phone right now.

**Comment by alex6480** [comment]
I am closing this, as I have created separate issues for your suggestions.
