### ISSUE TITLE
notes field

### ISSUE THREAD

**Issue by lephtHanded** [assetgrid/assetgridapp#40]
**Is your feature request related to a problem? Please describe.**
No problem, looks great, love the dashboard.

**Describe the solution you'd like**
I was confused at first about the _Description_ field.  I wanted to put in there, "Breakfast with the kids"  because we went to Waffle House this morning.  If I import from my bank, _Description_ is where I spent the money so that makes sense for searching for transactions by where you spent your money.
I guess I'm just looking for a possible blank field where I can add some context.
Like if I had a car expense, it would look like this:

- Description: Costco
- Category: Auto-repair
- Notes: new tires for the wife's car 

**Describe alternatives you've considered**
I thought about adding a lot of data to the _description_ field but I think its messy that way

**Additional context**
N/A

**Comment by alex6480** [comment]
It is planned. Instead of adding just a note field, I will make it possible to add custom fields to transactions, so you can store any information as you want.

This is a bit more technical to implement than just a note field, so it will take some time, but it's coming.

**Comment by lephtHanded** [comment]
> 

swank!  
would there be a way to add the custom field during import?

**Comment by alex6480** [comment]
Yes. The import tool will be expanded so you can set the value of any custom field you add during import.

I'm closing this issue as it is a duplicate of #27
