### ISSUE TITLE
Contractors / recipients

### ISSUE THREAD

**Issue by SlawekJ-G** [assetgrid/assetgridapp#49]
When adding a transaction, I would like to have possibility to choose 'contractor', so I can see in which shop, to whom, I've spent my money.

If you do not plan to implement it, then maybe as workaround tags can be used... just thinking.
Or - maybe destination field, when I transfer money between my accounts I can put my other account here, but when I spent money, I can choose where I have paid.

**Comment by alex6480** [comment]
Just create an account. If you don't check "include in net worth", Assetgrid will know that it's not your account.
