### ISSUE TITLE
Feature request: money transfers between own accounts

### ISSUE THREAD

**Issue by SlawekJ-G** [assetgrid/assetgridapp#50]
I am using accounts in the suggested way, that MY accounts are included in the net worth.
Now, when I transfer money between such accounts, on the Dashboard, such transactions are shown as Expense / Revenue.
In my opinion it makes confusion, as such transaction is not an expense at all, I do not own less money because of transaction between my account.
I think filtering transactions when transfer is between accounts, which are included (both) in net worth would make Dashboard more closer to the reality.

**Comment by alex6480** [comment]
Thanks for the suggestion. In the next release, transfers will be shown separately in the category chart and the cashflow chart on the account page.

In the cashflow chart on the dashboard, transfers will be excluded entirely.

![billede](https://user-images.githubusercontent.com/8026279/196678366-8a8a7172-74db-4f45-bd30-74e39959b2ba.png)

**Comment by alex6480** [comment]
Added in v0.2.1
