### ISSUE TITLE
add column sorting (at least on date and amount fields)

### ISSUE THREAD

**Issue by stalsma** [assetgrid/assetgridapp#53]
Would be nice to sort by date (ascending) instead of being locked into descending.  Also, sort by amount would be useful when trying to find a specific transaction.

**Comment by alex6480** [comment]
This should be possible already. Just click the table header on the column you want to sort. Can you send a screenshot of where the sort isn't working?

Though I can see that sorting on accounts and categories seems to be broken at the moment.

**Comment by stalsma** [comment]
I'm using the latest docker image I pulled this morning, testing in Brave and Edge.  Nothing happens when I click the headers. 

I checked the network tab, and didn't see any missing libraries.

![image](https://user-images.githubusercontent.com/5501817/196729621-92966085-9e04-44ee-9c90-ef69fb6ad1ba.png)

There's a bunch of identical warnings in the docker log:

```
Compiling a query which loads related collections for more than one collection navigation, either via 'Include' or through projection, but no 'QuerySplittingBehavior' has been configured. By default, Entity Framework will use 'QuerySplittingBehavior.SingleQuery', which can potentially result in slow query performance. See https://go.microsoft.com/fwlink/?linkid=2134277 for more information. To identify the query that's triggering this warning call 'ConfigureWarnings(w => w.Throw(RelationalEventId.MultipleCollectionIncludeWarning))'.
```

but I think those only appear on container startup.

**Comment by alex6480** [comment]
You can only sort on the transaction page. 
The reason you cannot sort on the account page, is that this page displays a balance, which would be too expensive to compute, if transactions weren't ordered by time.

You can use the advanced search to only show transactions from a specific account.

**Comment by stalsma** [comment]
Oops--found it.  Just unfamiliar w/the interface.  

As I played around with the filters to try what you suggested, I discovered some more weirdness.  

1. Without filters, page to something higher (e.g. 10)
2. Apply a filter that returns fewer pages than the current page your one
3. No results are displayed

Probably need to reset page index to something (0?) when results get filtered.

(Would also be very useful to save a search profile, like you can same import profiles.  E.g. deposit from acct x from last year.)
