### ISSUE TITLE
Balance column incorrect for accounts spanning multiple years if timespan doesn't match length of accont

### ISSUE THREAD

**Issue by stalsma** [assetgrid/assetgridapp#57]
**Describe the bug**
I imported 2 years of data from an account (2021, 2022).  The balance in the account is correct.

But if I only show data from 2022 (or from Oct 2022), the starting balance is essentially 0, so the running balance is off.

Strangely enough, the graph seems to show the correct starting balance, so the hard work is probably done.

**Screenshots**
![image](https://user-images.githubusercontent.com/5501817/196895898-46e48c48-2067-400c-a895-523e29bf82f3.png)

**Comment by alex6480** [comment]
Solved in v0.2.2
