### ISSUE TITLE
 Microsoft.EntityFrameworkCore.Model.Validation[10620]

### ISSUE THREAD

**Issue by ajnasaboobacker** [assetgrid/assetgridapp#62]
After deploying the docker container the below enter showed up on the logs. 

warn: Microsoft.EntityFrameworkCore.Model.Validation[10620]
      The property 'TransactionAutomation.Actions' is a collection or enumeration type with a value converter but with no value comparer. Set a value comparer to ensure the collection/enumeration elements are compared correctly.

Architecture used : ARM (Raspberry Pi 4)

docker compose used:

version: "3.1"
  services:
    db:
      image: mariadb:latest
      container_name: mariadb
      volumes:
        -  ./mariadb:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: secret

    assetgrid:
      image: assetgrid/assetgrid
      container_name: assetgrid
      links:
        - db:db
      environment:
        CONNECTION_STRING: "Server=db;Database=assetgrid;Uid=assetgrid;Pwd=secret"
      ports:
        - 80:8080

**Comment by alex6480** [comment]
The warning doesn't affect anything, but it is solved in the release.
